/**************************
  Код для Oracle
***************************/
DROP TABLE agrmnt;
DROP TABLE agrmnt_res;

CREATE TABLE agrmnt (id NUMBER GENERATED BY DEFAULT AS IDENTITY,
					 agrmnt varchar2(100),
					 period DATE,
				 	 agrmnt_sum NUMBER,
				 	 type_operation char(1),
				 	 load_date date DEFAULT sysdate,
				 	 type_dml char(1) DEFAULT 'I')
	   PARTITION BY RANGE (agrmnt) (PARTITION agrmnt_prt VALUES LESS THAN (MAXVALUE));
CREATE INDEX idx_agrmnt_01 ON agrmnt (agrmnt);
						   
-- Генерируем данные
BEGIN
 DELETE agrmnt;
 -- Пишем начисления
 FOR agr IN (SELECT '001/01/'||dbms_random.string('U',9) agrmnt, round(dbms_random.value(1000,2000),2) agrmnt_sum, 'A' type_operation FROM dual CONNECT BY LEVEL <= 2)
 LOOP
  FOR pr IN (SELECT ADD_MONTHS(trunc(sysdate,'yyyy'),LEVEL-1) period FROM dual CONNECT BY 0+LEVEL < 13)
  LOOP
	INSERT INTO agrmnt (agrmnt, period, agrmnt_sum, type_operation) VALUES (agr.agrmnt, pr.period, agr.agrmnt_sum, agr.type_operation);  	
  END LOOP;
 END LOOP;

 -- Пишем оплаты, делаем так что может образоваться по итогу оплат либо перебор либо недобор
 FOR agr IN (SELECT agrmnt, period+dbms_random.value(1,20) period, round(dbms_random.value(sum(agrmnt_sum)-100,sum(agrmnt_sum)+100),2) agrmnt_sum, 'P' type_operation  
  			   FROM agrmnt
  			  GROUP BY agrmnt, period)
 LOOP
  INSERT INTO agrmnt (agrmnt, period, agrmnt_sum, type_operation) VALUES (agr.agrmnt, agr.period, agr.agrmnt_sum, agr.type_operation);  	
 END LOOP;
 COMMIT;
END;

SELECT agrmnt, type_operation, sum(agrmnt_sum) agrmnt_sum FROM agrmnt GROUP BY agrmnt, type_operation;

WITH tmp_agrmnt_a AS (SELECT agrmnt, period, sum(agrmnt_sum) agrmnt_sum
 					    FROM agrmnt
 					   WHERE type_operation = 'A'
 					   GROUP BY agrmnt, period),
 	 tmp_agrmnt_p AS (SELECT agrmnt, sum(agrmnt_sum) agrmnt_sum
 	 					FROM agrmnt
 	 				   WHERE type_operation = 'P'
 	 				   GROUP BY agrmnt)	
SELECT a.agrmnt, 
	   a.period, 
	   a.agrmnt_sum agrmnt_sum_a, 
	   p.agrmnt_sum*ratio_to_report(a.agrmnt_sum) OVER (PARTITION BY a.agrmnt) agrmnt_sum_p
  FROM tmp_agrmnt_a a
  JOIN tmp_agrmnt_p p ON (a.agrmnt = p.agrmnt)
  
  
